import {
    Activity,
    Baby,
    Bone,
    Brain,
    Eye,
    HeartPulse,
    Microscope,
    Pill,
    Smile,
    Stethoscope,
} from "lucide-react";

export const SPECIALITY_ICONS = {
    Cardiology: HeartPulse,
    Neurology: Brain,
    Ophthalmology: Eye,
    Orthopedics: Bone,
    Pediatrics: Baby,
    Dentistry: Smile,
    General: Stethoscope,
    Pathology: Microscope,
    Physician: Activity,
    Pharmacy: Pill,
    Cardiologist: HeartPulse,
    "DM (Cardio)": HeartPulse,
    "DNB (Cardio)": HeartPulse,
    DM: HeartPulse,
    Neurologist: Brain,
    "Neuro Physician": Brain,
    MCh: Brain,
    Psychiatrist: Brain,
    DPM: Brain,
    "Consultant Physician": Activity,
    MD: Activity,
    "DNB (Medicine)": Activity,
    FCCP: Activity,
    Nephrologist: Activity,
    "DNB (Nephro)": Activity,
    "General Practitioner": Stethoscope,
    LSGP: Stethoscope,
    DNB: Stethoscope,
    Diabetologist: Pill,
    "DIP.DIAB": Pill,
    Endocrinologists: Pill,
    "DNB (Endo)": Pill,
    "DM (Endo)": Pill,
    Rheumatologist: Bone,
};
