import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import AuthProvider from "@/providers/authProvider";
import QueryClientProvider from "@/providers/queryClient";
import { ThemeProvider } from "@/providers/themeProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
            suppressHydrationWarning
        >
            <body className="flex h-full w-full bg-neutral-50 dark:bg-neutral-900 overflow-hidden">
                <QueryClientProvider>
                    <TooltipProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="light"
                            enableSystem
                            disableTransitionOnChange
                            suppressHydrationWarning
                        >
                            <AuthProvider>
                                {children}
                                <Toaster richColors />
                            </AuthProvider>
                        </ThemeProvider>
                    </TooltipProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
